"""empty message

Revision ID: 75adb00a6df1
Revises: 90f5ebaa602f
Create Date: 2021-04-04 22:15:05.022191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75adb00a6df1'
down_revision = '90f5ebaa602f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('description', table_name='sale')
    op.drop_index('money_USD', table_name='sale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('money_USD', 'sale', ['money_USD'], unique=True)
    op.create_index('description', 'sale', ['description'], unique=True)
    # ### end Alembic commands ###
